export enum ErrorType {
  INVALID_ORDER = 'INVALID_ORDER',
  InvalidToken = 'INVALID_TOKEN',
  AccessTokenExpired = 'ACCESS_TOKEN_EXPIRED',
  RefreshTokenExpired = 'REFRESH_TOKEN_EXPIRED',
  PermissionExists = 'PERMISSION_EXISTS',
  RoleExists = 'ROLE_EXISTS',
  SlugExists = 'SLUG_EXISTS',
  Exists = 'EXISTS',
  UserExists = 'USER_EXISTS',
  AddressLimit = 'ADDRESS_LIMIT',
  EnumType = 'ENUM_TYPE',
  FileType = 'FILE_TYPE',
  InvalidCurrentPassword = 'INVALID_CURRENT_PASSWORD',
  InvalidCredentials = 'INVALID_CREDENTIALS',
  BlockedUser = 'BLOCKED_USER',
  InactiveUser = 'INACTIVE_USER',
  ForeignKeyConflict = 'FOREIGN_KEY_CONFLICT',
  UserAlreadySignedout = 'USER_ALREADY_SIGNED_OUT',
  OtpServer = 'OTP_SERVER',
  MarketLimit = 'MARKET_LIMIT',
  AlreadyTakenCart = 'CART_ALREADY_TAKEN',
  AlreadyTakenOrder = 'ORDER_ALREADY_TAKEN',
  NotFoundException = 'NOT_FOUND',
  Forbidden = 'FORBIDDEN_REQUEST',
  Conflict = 'CONFLICT_DATA',
  InternalServer = 'INTERNAL_SERVER_ERROR',
}
